İleriWeb.Web/Controllers/ProductsController.cs
using AutoMapper;
using IleriWeb.Core.DTOs;
using IleriWeb.Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using IleriWeb.Core;
using IleriWeb.Core.Models;
using IleriWeb.Core.Repositories;
using IleriWeb.Repository;
using Microsoft.AspNetCore.Authorization;

namespace IleriWeb.Web.Controllers
{
	[AllowAnonymous]
	public class ProductsController : Controller
    {
        private readonly IProductService _services;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        
        private readonly IOrderService _orderService;
        private readonly AppDbContext _context;


        public ProductsController(IProductService services, ICategoryService categoryService, IMapper mapper, IOrderService orderService, AppDbContext context)
        {
            _services = services;
            _categoryService = categoryService;
            _mapper = mapper;
            _orderService = orderService;
            
            _context = context;
        }





		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var products= await _services.GetProductsWithDetails();
			return View(products);
		}


		[HttpGet]
		public async Task<IActionResult> ProductDetails(int id)
        {

            var product = await _services.GetProductDetailsWithIdAsync(id);


			return View(product);
		}

		[HttpPost]
		public ActionResult SubmitData(AddToCartWithQuantityDTO model)
		{
			if (ModelState.IsValid)
			{
				TempData["ProductId"] = model.ProductId;
				TempData["Quantity"] = model.Quantity;

				// İkinci View'e yönlendir
				return RedirectToAction("AddToCartWithQuantity","Cart");
			}

			return View("ProductDetails", model);
		}


		public async Task<IActionResult> deneme()
		{




			var orderr = new Order
			{
				OrderDate = DateTime.UtcNow,
				IdentityUserId = 7,
				OrderDetails = new OrderDetail
				{

					ProductId = 11,
					Quantity = 3
				}
			};

			await _orderService.AddAsync(orderr);


			return RedirectToAction("index");



		}

		




	}
}

İleriWeb.Web/Controllers/UserController.cs
using AutoMapper;
using IleriWeb.Core.DTOs;
using IleriWeb.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IleriWeb.Web.Controllers
{
	[AllowAnonymous]
	public class UserController : Controller
    {

        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMapper _mapper;
        public UserController(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IMapper mapper)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserSignUpDto u)
        {
            if (ModelState.IsValid)
            {




                ApplicationUser user = new ApplicationUser()
                {
                    Email = u.Mail,
                    UserName = u.UserName,
                    FullName = u.NameSurname

                };

                

                var result = await userManager.CreateAsync(user, u.Password);

                if (result.Succeeded)
                {
                    

                    return RedirectToAction("login", "user");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);

                    }
                }

            }



            return View(u);
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserSignInViewModel s)
        {



            if (ModelState.IsValid)
            {

                var result = await signInManager.PasswordSignInAsync(s.username, s.password, true, true);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }
                else
                {
                    return View();
                }


            }

            return View();
        }


        public async Task<IActionResult> Logout()
        {

            await signInManager.SignOutAsync();
            return RedirectToAction("login", "user");
        }


        public async Task<IActionResult> AccessDenied()
        {

            return View();
        }


    }
}

İleriWeb.Web/Views/Shared/Components/UserButtons/Default.cshtml
@using IleriWeb.Web.Helpers
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
	var basket = ViewData["Basket"] as Basket;
	decimal TotalPrice = 0;
	var Currency = (string?)HttpContextAccessor.HttpContext?.Items["Currency"];
	var rate = (double?)HttpContextAccessor.HttpContext?.Items["CurrencyRate"];
									
}﻿

@if (ViewBag.CurrentUser == null)
{
	<div class="col-md-3 clearfix">
		<div class="header-ctn">
			<div>
				
				<a  asp-area="" asp-controller="User" asp-action="Register">
					<i class="fa fa-user-plus"></i>
					Sign up
				</a>

			</div>

			<div>
				
				<a asp-area="" asp-controller="User" asp-action="Login">
					<i class="fa fa-sign-in"></i>
					Login
				</a>
			</div>
		</div>
	</div>


	
}
else
{
	

	
	
	<!-- ACCOUNT -->
	<div class="col-md-4 clearfix">
		<div class="header-ctn">

			

			
			<div>
				<a asp-area="" asp-controller="User" asp-action="Logout">
					<i class="fa fa-sign-out"></i>
					<span>Log Out</span>

				</a>
			</div>

			<!-- Cart -->
			<div class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
					<i class="fa fa-shopping-cart"></i>
					<span>Your Cart</span>
					<div class="qty">@basket.Items.Count</div>
				</a>
				<div class="cart-dropdown">
					<div class="cart-list">

						@foreach (var item in basket.Items)
						{
							<div class="product-widget">
								<div class="product-img">
									@{
										var base64 = Convert.ToBase64String(item.Product.ImageData);
										var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
									}
									<img src="@imgSrc" />
								</div>
								<div class="product-body">
									<h3 class="product-name"><a href="#">@item.Product.Name</a></h3>

									<h4 class="product-price"><span class="qty">@item.Quantity x</span> @CurrencyHelper.ConvertCurrency(item.TotalPrice, rate) @Currency </h4>
									
								</div>
								<button class="delete" onclick="window.location.href='/Cart/RemoveFromCart/@item.Id'"><i class="fa fa-close"></i></button>
							</div>
						}





					</div>
					<div class="cart-summary">
						<small>@basket.Items.Count Item(s) selected</small>
						<h5>
							@foreach (var i in basket.Items)
							{
								TotalPrice += @CurrencyHelper.ConvertCurrency(i.TotalPrice, rate);

							}
							SUBTOTAL:  @TotalPrice @Currency
						</h5>
					</div>
					<div class="cart-btns">
						<a href="#">View Cart</a>
						<a href="cart/index">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
					</div>
				</div>
			</div>
			<!-- /Cart -->

			

			@if (ViewBag.IsInRole == true)
			{
				<div>
					<a asp-area="admin" asp-controller="Products" asp-action="index">
						<i class="fa fa-bars"></i>
						<span>Admin Panel</span>

					</a>
				</div>

			}
			
		</div>
	</div>
	<!-- /ACCOUNT -->
}