İleriWeb.Web/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using IleriWeb.Core.DTOs;
using IleriWeb.Core.Models;
using IleriWeb.Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IleriWeb.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Policy = "AdminPolicy")]
    public class CategoryController : Controller
	{
		private readonly ICategoryService _categoryService;
		private readonly IMapper _mapper;

		public CategoryController(ICategoryService categoryService, IMapper mapper)
		{
			_categoryService = categoryService;
			_mapper = mapper;
		}

		public async Task<IActionResult> Index()
		{
			var categories = await _categoryService.GetAllAsync();
			var categoriesDto = _mapper.Map<List<CategoryDto>>(categories.ToList());

			return View(categoriesDto);
		}

        public IActionResult Create()
        {


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryDto categoryDto)
        {

            byte[] imageData;
            using (var memoryStream = new MemoryStream())
            {
                await categoryDto.imageFile.CopyToAsync(memoryStream);
                imageData = memoryStream.ToArray();

            }

            if (ModelState.IsValid)
            {
                var category = _mapper.Map<Category>(categoryDto);
                category.ImageData = imageData;
                await _categoryService.AddAsync(_mapper.Map<Category>(category));
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

İleriWeb.Web/Controllers/ProductsController.cs
using AutoMapper;
using IleriWeb.Core.DTOs;
using IleriWeb.Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using IleriWeb.Core;
using IleriWeb.Core.Models;
using IleriWeb.Core.Repositories;
using IleriWeb.Repository;
using Microsoft.AspNetCore.Authorization;

namespace IleriWeb.Web.Controllers
{
	[AllowAnonymous]
	public class ProductsController : Controller
    {
        private readonly IProductService _services;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        
        private readonly IOrderService _orderService;
        private readonly AppDbContext _context;


        public ProductsController(IProductService services, ICategoryService categoryService, IMapper mapper, IOrderService orderService, AppDbContext context)
        {
            _services = services;
            _categoryService = categoryService;
            _mapper = mapper;
            _orderService = orderService;
            
            _context = context;
        }





		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var products= await _services.GetProductsWithDetails();
			return View(products);
		}


		[HttpGet]
		public async Task<IActionResult> ProductDetails(int id)
        {

            var product = await _services.GetProductDetailsWithIdAsync(id);


			return View(product);
		}

		[HttpPost]
		public ActionResult SubmitData(AddToCartWithQuantityDTO model)
		{
			if (ModelState.IsValid)
			{
				TempData["ProductId"] = model.ProductId;
				TempData["Quantity"] = model.Quantity;

				// İkinci View'e yönlendir
				return RedirectToAction("AddToCartWithQuantity","Cart");
			}

			return View("ProductDetails", model);
		}


		public async Task<IActionResult> deneme()
		{




			var orderr = new Order
			{
				OrderDate = DateTime.UtcNow,
				IdentityUserId = 7,
				OrderDetails = new OrderDetail
				{

					ProductId = 11,
					Quantity = 3
				}
			};

			await _orderService.AddAsync(orderr);


			return RedirectToAction("index");



		}

		




	}
}

İleriWeb.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IleriWeb.Web</title>


	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="~/CommerceAssets/css/bootstrap.min.css" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="~/CommerceAssets/css/slick.css" />
	<link type="text/css" rel="stylesheet" href="~/CommerceAssets/css/slick-theme.css" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="~/CommerceAssets/css/nouislider.min.css" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="~/CommerceAssets/css/font-awesome.min.css">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="~/CommerceAssets/css/style.css" />


  
</head>
<body>
   


	<!-- HEADER -->
	<header>

		
		
		<!-- MAIN HEADER -->
		<div id="header">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- LOGO -->
					<div class="col-md-3">
						<div class="header-logo">
							<a href="/Home" class="logo">
								<h2 style="color:white">ADMIN PANEL</h2>
							</a>
						</div>
					</div>

					<!-- Space -->
					<div class="col-md-5">
						
					</div>
					
					@await Component.InvokeAsync("AdminButtons")
					
				</div>
				<!-- row -->
			</div>
			<!-- container -->
		</div>
		<!-- /MAIN HEADER -->
	</header>
	<!-- /HEADER -->
	<!-- NAVIGATION -->
	<nav id="navigation">
		<!-- container -->
		<div class="container">
			<!-- responsive-nav -->
			<div id="responsive-nav">
				<!-- NAV -->
				<ul class="main-nav nav navbar-nav">
					<li ><a class="nav-link text-dark" asp-area="admin" asp-controller="Products" asp-action="Index">Products</a></li>
					
					<li><a class="nav-link text-dark" asp-area="admin" asp-controller="Category" asp-action="Index">Categories</a></li>

				</ul>
				<!-- /NAV -->
			</div>
			<!-- /responsive-nav -->
		</div>
		<!-- /container -->
	</nav>
	<!-- /NAVIGATION -->
	

	
		<div class="container">
		@RenderBody()
		</div>
        
            
       
    

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IleriWeb.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>